### ISSUE TITLE
Broken compatibility: periodic_plot

### ISSUE THREAD

**Issue by DannyVanpoucke** [lmmentel/mendeleev#101]
## Describe the bug
periodic_plot seems no longer available in mendeleev (manual has no information whatsoever on the status, where it went, how it should be replaced)

## To Reproduce
#code from a working script (yes I am aware it is not a minimal example, but it shows what the goal is, and what should be "replaced", though that can not be traced by a normal user)
#Plot charges as periodic table
```python
ptable = fetch_table('elements') #get a pandas periodic table of elements

#panda = pd.DataFrame(columns=['metal','formula','Qform','Qm_avg','Qm_std','Qo_avg','Qo_std'])
eldict = [dict(),dict(),dict(),dict(),dict(),dict()] #one dictionary per formal charge
for i, row in panda.iterrows():
    eldict[row['Qform']-1][row['metal']] = row['Qo_avg']
#transform from string to Z-number
for OX in range(6):
    #print('OX=',OX,' len eldict=',len(eldict))
    allels = dict([(element(x[0]).atomic_number,x[1]) for x in eldict[OX].items()])
    for i in range(1,119):
        if i not in allels.keys():
            allels[i] = float("NaN") # use NaN to exclude missing data
    temp = pd.DataFrame(allels.items(),index=allels.keys()).sort_values(by=0)
    Ocharges = temp[1].astype('float32').round(3)
    ptable['OX'+str(OX+1)] = [np.round(x,3) if np.isnan(x) == False else float("NaN") for x in Ocharges ]
    periodic_plot(ptable, attribute='OX'+str(OX+1), colorby='attribute',
              title='Oxygen charge for metal oxidation number = '+str(OX+1),decimals=3)
```    

No need to reproduce

## Expected behavior
A clear description of what the "new" function should be that replaces 
```python
 periodic_plot(ptable, attribute='OX'+str(OX+1), colorby='attribute',
              title='Oxygen charge for metal oxidation number = '+str(OX+1),decimals=3)
```
with the settings which would translate from this previous version.

## Additional context
Annoyance by lack of documentation and compatibility of subversions of the package

**Comment by lmmentel** [comment]
Thanks for reporting this @DannyVanpoucke!

You are right, the docs could use some more work. There were a few API changes between version but those changes are only documented in [the changelog](https://mendeleev.readthedocs.io/en/latest/changes_link.html). It seems that the last version to have `periodic_plot` was 0.7.0 a while back.


Since then the are three visualization methods:
- [periodic_table]()

**Comment by DannyVanpoucke** [comment]
An API reference describing the attributes would be nice, as according to the tutorial this should work smoothly:
ptable = fetch_table('elements')
#(then we add a column with name OX1)
OX=0
periodic_table(ptable, attribute="OX1", colorby='attribute',   title='Oxygen charge for metal oxidation number = '+str(OX+1),decimals=3)
but gives the error:

TypeError: periodic_table() got multiple values for argument 'attribute'

and using the "periodic_table_bokeh" function it dies painfully:
--------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File D:\10_Software\13_Anaconda3\lib\site-packages\pandas\core\indexes\base.py:3629, in Index.get_loc(self, key, method, tolerance)
   3628 try:
-> 3629     return self._engine.get_loc(casted_key)
   3630 except KeyError as err:

File D:\10_Software\13_Anaconda3\lib\site-packages\pandas\_libs\index.pyx:136, in pandas._libs.index.IndexEngine.get_loc()

File D:\10_Software\13_Anaconda3\lib\site-packages\pandas\_libs\index.pyx:163, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:5198, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:5206, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'y'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Input In [12], in <cell line: 9>()
     21 atname = 'OX'+str(OX+1)
     22 print(atname,type(atname))
---> 23 periodic_table_bokeh(ptable, attribute="OX1", colorby='attribute',
     24           title='Oxygen charge for metal oxidation number = '+str(OX+1),decimals=3)

File D:\10_Software\13_Anaconda3\lib\site-packages\mendeleev\vis\bokeh.py:42, in periodic_table_bokeh(elements, attribute, cmap, colorby, decimals, height, missing, title, wide_layout, width)
     24 """
     25 Use Bokeh to plot the periodic table data contained in the `df`
     26 
   (...)
     37     width : Width of the figure in pixels
     38 """
     40 # additional columns for positioning of the text
---> 42 elements.loc[:, "y_anumber"] = elements["y"] - 0.3
     43 elements.loc[:, "y_name"] = elements["y"] + 0.2
     45 if attribute:

File D:\10_Software\13_Anaconda3\lib\site-packages\pandas\core\frame.py:3505, in DataFrame.__getitem__(self, key)
   3503 if self.columns.nlevels > 1:
   3504     return self._getitem_multilevel(key)
-> 3505 indexer = self.columns.get_loc(key)
   3506 if is_integer(indexer):
   3507     indexer = [indexer]

File D:\10_Software\13_Anaconda3\lib\site-packages\pandas\core\indexes\base.py:3631, in Index.get_loc(self, key, method, tolerance)
   3629     return self._engine.get_loc(casted_key)
   3630 except KeyError as err:
-> 3631     raise KeyError(key) from err
   3632 except TypeError:
   3633     # If we have a listlike key, _check_indexing_error will raise
   3634     #  InvalidIndexError. Otherwise we fall through and re-raise
   3635     #  the TypeError.
   3636     self._check_indexing_error(key)

KeyError: 'y'

**Comment by lmmentel** [comment]
Thanks for the extra information. I'll look into it. I already added an issue to add api docs for vis module #102. 

In the first example you shared I think you are passing an extra `ptable` argument that's not required. Could you try:

```python
from mendeleev.vis import periodic_table
periodic_table()
```
just to verify that the simplest case works?

For your specific case you share a reproducible example I could use?

It would help if you could share an which python version you are on and your mendeleev version.

Could you also use [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) when sharing code blocks? It speeds up reading code a bit.

**Comment by lmmentel** [comment]
I've added api documentation on the vis module in #105, hope it helps.

As far as your example goes here are some thoughts that might help:
-  `periodic_plot` function covers high level plotting functionality, which means it does not take a dataframe as an argument and only the attribute name to be plotted. It fetches the "most common" data itself and calls on of the two plotting backends: `plotly` or `bokeh` for doing the heavy lifting 
- `periodic_table_plotly` and `periodic_table_bokeh` are lower level functions where you can pass you own dataframe with elements or custom computed properties **but** you'' need to have `x` and `y` columns for each element. You can add those coordinates with `mendeleev.utils.create_vis_dataframe` function.

I think the errors you are seeing are a consequence of either passing a dataframe when not required or not having `x` and `y` columns for lower level functions. 

I hope with some of the extra documentation it'll be clearer but if you see ways it can be improved, please let me know.
