### ISSUE TITLE
SQLAlchemy `declarative_base` deprecation

### ISSUE THREAD

**Issue by BvB93** [lmmentel/mendeleev#106]
As of SQLAlchemy 2.0 the location of its `declarative_base()` function has been moved, deprecating its old import path that's still used by mendeleev. It's only a deprecation warning for now, though it's still non-ideal that this automatically pops up when importing from mendeleev.

```
   /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mendeleev/models.py:43: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base()
```

## Specification

- mendleev version: 0.13.0
- python version: 3.11.3
- platform: Ubuntu-22.04

**Comment by lmmentel** [comment]
Thanks for reporting @BvB93 :+1:  I must've missed the warning. Should be an easy fix.
