### ISSUE TITLE
Phase transition data on allotropes

### ISSUE THREAD

**Issue by Eben60** [lmmentel/mendeleev#117]
For gray tin, the melting point of 286.35 K is given. This is actually the temperature of the transition between the two crystalline modifications of tin (gray tin definitely does not melt at room temperature).

For diamond, the melting point of 4713.15 (4500°C) is given. Diamond is actually thermodynamically unstable at 1 bar, and according to Wikipedia rapidly converts to graphite at 4500 K and above. Thus I doubt you can actually melt it. 

For phosphorus, it is even more interesting. White phosphorus, though thermodinamically unstable, can indeed be melt at well-defined temperature of 317.3 K. The thermodynamically stable forms violett (above 550°C) and black (<550°C) are uncommon and are not contained in your database.

For oxygen, ozone is lacking, which is actually a well-definded substance.

(I didn't try to check all data)

I'm not sure what can be done with all that, as I'm afraid the "allotropic rabbit hole" can be arbitrarily deep, with many (most?) allotropic forms being actually metastable. I'd probably just list all allotropes, but provide the phase transition just for one form, the stable or the most common one.

**Comment by lmmentel** [comment]
Thanks for reporting this but I'm not sure what's a practical way forward. You are right that there is nuance in the reported numbers but those nuances are well explained in the [data source](https://mendeleev.readthedocs.io/en/stable/bibliography.html#id73) I quote in the reference documentation. Where possible I'm following the same conventions that the source introduced but for obvious reasons I'm concerned with the actual data. I encourage you to check out the data source to find how the source numbers are reported and If you have any suggestions for changes I'm more than happy to continue the discussion.

**Comment by lmmentel** [comment]
Closing as stale. Feel free to reopen if you want to continue the discussion.
