### ISSUE TITLE
How to add color bar to the plots

### ISSUE THREAD

**Issue by yanghan234** [lmmentel/mendeleev#127]
Dear developers,

I'm trying to plot the periodic table with my own element-wise data, and I want to add a color bar to the plot. Is there any temporary solution for this? Thank you!

**Comment by lmmentel** [comment]
Hey! It would be much easier to help if you provide a concrete case you're dealing with, i.e. self-contained code, reproducible code example.

Current plotting backends mendeleev use plotly and bokeh and plotting functions return `Figure` object which can be further modified. Here's an [example](https://community.plotly.com/t/how-do-i-add-a-colorbar-to-an-already-existing-graph/21571/5) on how to add a colorbar to existing plotly figure.
