### ISSUE TITLE
ImportError: module 'mendeleev' has no element with symbol 'fetch'

### ISSUE THREAD

**Issue by GCS-ZHN** [lmmentel/mendeleev#147]
## Describe the bug
Fail to import `mendeleev.fetch` submodule by `from mendeleev import fetch` due to the definition of `mendeleev.__getattr__` function. 

```python
>>> from mendeleev import fetch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/HOME/scw6byf/run/miniconda3/lib/python3.10/site-packages/mendeleev/__init__.py", line 153, in __getattr__
    raise ImportError(
ImportError: module 'mendeleev' has no element with symbol 'fetch', please check you spelling
```

## Specification

- mendleev 0.16.0
- python 3.10
- platform MacOS

**Comment by lmmentel** [comment]
Thanks a lot for reporting this. It's a bit surprising this wasn't caught by any of the tests. I'll have a look later this week.

In the meantime, downgrading to v0.15.0 should work.
