### ISSUE TITLE
df = fetch_table('elements') its not working its showing the error AttributeError: 'OptionEngine' object has no attribute 'execute'

### ISSUE THREAD

**Issue by 93-hsngit** [lmmentel/mendeleev#158]
## Describe the bug
from mendeleev.fetch import fetch_table
from mendeleev.db import get_session, get_engine

df = fetch_table('elements')

AttributeError: 'OptionEngine' object has no attribute 'execute'

**Comment by 93-hsngit** [comment]
AttributeError: 'OptionEngine' object has no attribute 'execute'

**Comment by lmmentel** [comment]
Thanks @93-hsngit, could you say what version of mendeleev you are using?

**Comment by lmmentel** [comment]
I just tried to reproduce with the latest version (0.16.2) and didn't get any errors:

```python
In [1]: from mendeleev.fetch import fetch_table, get_engine

In [2]: df = fetch_table("elements")

In [3]: df.head()
Out[3]: 
                                          annotation  atomic_number  atomic_radius  atomic_volume block  ...  mendeleev_number dipole_polarizability_unc  pettifor_number  glawe_number molar_heat_capacity
0  density(@ -253C), evaporation_heat(H-H), fusio...              1           25.0           14.1     s  ...               105                   0.00003            103.0         103.0              28.836
1                                 density(@ -270C),               2          120.0           31.8     s  ...               112                   0.00002              1.0           1.0              20.786
2                                                                 3          145.0           13.1     s  ...                 1                   0.00050             12.0          12.0              24.860
3                                                                 4          105.0            5.0     s  ...                75                   0.03000             77.0          77.0              16.443
4                                                                 5           85.0            4.6     p  ...                81                   0.10000             86.0          86.0              11.087

[5 rows x 69 columns]

In [4]: import mendeleev

In [5]: mendeleev.__version__
Out[5]: '0.16.2'
```

**Comment by 93-hsngit** [comment]
I am Using the latest version.

**Comment by lmmentel** [comment]
Just to be sure, could you share what the following code produces with your installation:
```python
import mendeleev
print(mendeleev.__version__)
```

**Comment by lmmentel** [comment]
I googled around and discovered this might be related to sqlachemy version. I cannot reproduce your exact error but when I downgraded to sqlalchemy==1.4.52 I get this:

```python
...
AttributeError: 'Engine' object has no attribute 'cursor'
```

**Comment by 93-hsngit** [comment]
Please see the error

[image: image.png]
I import all the required mendeleev libraries (and in my pc
sqlalchemy==2.0.23)
[image: image.png]
Please help.

Regards
Hossain

**Comment by lmmentel** [comment]
@93-hsngit there is no image attached to your comment, maybe something went wrong? 

Right now I cannot reproduce your specific error and my suspicion is that it's something to do with dependencies so I please share the output of running https://github.com/lmmentel/mendeleev/issues/158#issuecomment-2133810359

**Comment by 93-hsngit** [comment]
mendeleev.__version__='0.16.2'
sqlalchemy.__version__='2.0.25'
pandas.__version__='1.5.3'

**Comment by lmmentel** [comment]
Thanks @93-hsngit, I was able to reproduce the same error with the combination of dependencies you shared. 

I started working on a solution in #159 but it might take some time to test against across relevant versions of dependencies. Overall this seems like a mismatch between major version of pandas and sqlalchemy but I hope I can find an api consistent between the version changes.

In the meantime you could upgrade your pandas versions to ">=2.0.0" and that should solve it for you.

**Comment by 93-hsngit** [comment]
Yahh..., now the problem get resolve after installing pandas==2.0.0, Thank you so much @lmmentel  Love your work
