### ISSUE TITLE
Include python 3.13 in testing and CI

### ISSUE THREAD

**Issue by lmmentel** [lmmentel/mendeleev#188]
**Is your feature request related to a problem? Please describe.**
Python 3.13.0 was recently released and it should be included in the test coverage.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ElricleNecro** [comment]
If I can add my 2 cents: unless there are changes that are known to break a package, we shouldn't add a version upper limit as this can have heavy impact on downstream package when not necessary.

(this is also in [poetry](https://python-poetry.org/docs/faq/#are-unbound-version-constraints-a-bad-idea) guidelines)

**Comment by lmmentel** [comment]
Thanks, do you have any specific packages in mind here?

**Comment by ElricleNecro** [comment]
I was mainly thinking about the python version.

**Comment by lmmentel** [comment]
OK got it. Without the upper bound for python it is very hard to practically lock the dependencies (I'm using poetry for dependency management) since a lot of the package like numpy and pandas have defensive upper bounds since they might not be compatible with dev versions of python.
