### ISSUE TITLE
Wrong electron configuration for Lawrencium

### ISSUE THREAD

**Issue by senwang2126** [lmmentel/mendeleev#189]
The electron configuration of Lawrencium in this package is given as [Rn] 5f¹⁴ 6d 7s², but it should be [Rn] 5f¹⁴ 7s² 7p.

**Comment by lmmentel** [comment]
Thanks, do you have a source for this?

**Comment by lmmentel** [comment]
You're right, I found the ground level on [NIST](https://physics.nist.gov/cgi-bin/ASD/ie.pl?spectra=Lr&submit=Retrieve+Data&units=1&format=0&order=0&at_num_out=on&sp_name_out=on&ion_charge_out=on&el_name_out=on&seq_out=on&shells_out=on&level_out=on&ion_conf_out=on&e_out=0&unc_out=on&biblio=on). I'll try to get that fixed.
