### ISSUE TITLE
Inconsistent presentation of thermophysical properties

### ISSUE THREAD

**Issue by ccokerlanl** [lmmentel/mendeleev#212]
# Description
The mendeleev Element object returns the melting and boiling temperatures, if they exist, at what appears to be the minimum pressure at which that phase transition may occur. As a result, the boiling point for carbon returned is less than the melting point for carbon. It is not clear to the user that this is the convention.

# Current Behavior

### Script

```
#!/usr/bin/env python
import mendeleev

# create element
carbon = mendeleev.element('C')

# print melting and boiling points
print(carbon.melting_point)
print(carbon.boiling_point)
```

### Output

```
>>>{'graphite': 4762.15, 'diamond': 4713.15}
>>>{'graphite': 4098.15, 'diamond': None}
```

### Discussion
Data from this Mendeleev carbon object present a boiling temperature (4762 K) for graphite that is lower than the its melting temperature for graphite (4098 K). According to the carbon phase diagram, Fig. 3 in [1], this melting temperature corresponds to the triple point (~10 GPa or ~100,000 atm), whereas the boiling temperature from this Mendeleev object appears to correspond to standard pressure (1 atm). 

[1] Wang, X., Scandolo, S., & Car, R. (2005). Carbon Phase Diagram from Ab Initio Molecular Dynamics. Phys. Rev. Lett., 95, 185701.

# Expected behavior
If the entire pressure-temperature phase relationship is not implemented, thermophysical properties (e.g. melt temperature, latent heat of fusion) are expected to be presented for standard pressure (1 atm) unless otherwise specified. If such a phase transition does not exist at standard pressure (e.g. carbon melt point), the thermophysical property should return None (or perhaps NaN or Inf if that is more useful). 

# Compute Environment Specification

- mendleev version 0.17
- python version 3.12.7
- RHEL

**Comment by ccokerlanl** [comment]
Edit: Fixed a typo.

**Comment by ccokerlanl** [comment]
Edit: added a discussion and reference to the example.

**Comment by ccokerlanl** [comment]
Edit: fixed markdown heading levels.

**Comment by lmmentel** [comment]
I've verified that indeed the melting and boiling point might be misleading. The values are taken straight from the `PhaseTransition`  object but the crucial context is missing. It'll be safer to return `None` in those cases and leave users to dig through `PhaseTransition` data for further details.

**Comment by lmmentel** [comment]
Have a look at the PR #214 for the fix. I ended up dropping data for diamond since there was nothing available at the source at std conditions. There is a small example illustrating the changes, appreciate any feedback if that works.
