### ISSUE TITLE
Installation via terminal

### ISSUE THREAD

**Issue by Bellveron** [lmmentel/mendeleev#213]
Hello,

It's possible to add the installation via terminal on Linux distributions?
e.g. apt install python3-mendeleev

Thank you.

**Comment by lmmentel** [comment]
Thanks for the suggestion. Mendeleev supports installation via pip and conda and they both have CLI interfaces.

Is there something in your use case that prevents using the recommended tools?

**Comment by Bellveron** [comment]
Regarding pip, it prevents me, in Linux Mint, to install Mendeleev system-wide, requiring a virtual environment (check below):

#: pip install mendeleev
`error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
`
Regarding Conda, I don't want a package manager as I usually install them manually and system-wide, or manually into a virtual environment (inside venv) as needed.

As in this case I wish Mendeleev system-wide, pip it's preventing me and isn't desirable to install a "dependence" (Conda) just to be able to install Mendeleev.

Apologize-me for my English,
Thank you. I hope you understand.

**Comment by lmmentel** [comment]
Thanks, for the extra context. I think the system recommendation you got is pretty pretty good. The standard practice for python is isolating projects in virtual envs. Pushing a lot of 3rd party packages into system-wide installs creates a lot of complexity and unnecessary coupling between versions, not to mention how hard it might be to isolate and debug potential errors.

I strongly recommend installing `mendeleev` into a virtual env. If you want to emulate a system-wide install you could create a single venv and activate it whenever you launch a new shell (via .bashrc or whatever console you are using).

Packaging and maintaining mendeleev for linux distros is not something I have capacity for so unless you want to commit some time and make it work it's safe to assume that pypi and conda (and github releases) will stay as the main distribution channels.
