### ISSUE TITLE
Adapt the Mendeleev package to the Canadian spelling

### ISSUE THREAD

**Issue by AlanReviews** [lmmentel/mendeleev#27]
**Is your feature request related to a problem? Please describe.**
Yes. It is related to issue #25

**Describe the solution you'd like**
Is it possible to have the Mendeleev accept Canadian spelling of elements as arguments to the element() function such as Aluminium?

**Describe alternatives you've considered**

**Additional context**

**Comment by lmmentel** [comment]
Hi thanks for raising this but I at the moment I don't think it's worth effort since that change might require some work. Feel free though to submit a PR with a patch.
