### ISSUE TITLE
Inconsistency in density between Documentation and data

### ISSUE THREAD

**Issue by chelmes** [lmmentel/mendeleev#38]
For various gases (trials: N, He, O) density data is given at boiling point instead of at room temperature as suggested by documentation. 

- mendeleev 0.8.0
- python 3.6.8
- Unix

IMHO: Element Data should be updated to be consistent. Alternatively additional data for boiling point and room temperature densities could be provided

**Comment by lmmentel** [comment]
Thanks a lot for taking the time to submit the issue @chelmes . I'll have a look.

**Comment by lmmentel** [comment]
Could you share the source of data you are comparing the values against?

**Comment by chelmes** [comment]
I got the value from [wikipedia](https://en.wikipedia.org/wiki/Nitrogen), another example can be found [here] (https://www.lenntech.com/periodic/elements/n.htm)
