### ISSUE TITLE
Custom equality operator

### ISSUE THREAD

**Issue by mattwthompson** [lmmentel/mendeleev#42]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for creating this tool. I've been happy tinkering with it, but I've come across a small sharp edge. In testing, I have  habit of using `==` to compare a result to an expected value. This does not seem to work here since the `Element` class does not offer a custom equality operator:

```python3
>>> from mendeleev import element, O
>>> def f():
...     return element(8)
...
>>> assert f() == O
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> assert f() == element(8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> assert O == O  # passes
```
This is different from usage in other similar implementations, such as OpenMM:

```python3
>>> from openmm.app.element import Element
>>> assert Element.getByAtomicNumber(8) == Element.getByAtomicNumber(8)
```
**Describe the solution you'd like**
It would be useful for the `__eq__` operator to override the default `object.__eq__`, which defaults to `id`.  This can be overridden, probably with something that runs through each attribute and checks for them to be equal; I'd be happy to write up a PR if this sounds like a reasonable addition.

**Describe alternatives you've considered**

This can be worked around easily enough, i.e.
```python3
>>> assert f().symbol == O.symbol
```

**Comment by lmmentel** [comment]
Thanks for reporting this, let me have a look and come back to you. Could you describe your use in a bit more detail?

**Comment by mattwthompson** [comment]
The function above is a stripped-down version of a unit test; we want to pull down an atom from some chemical representation (topology, molecule, etc.) and make sure its element is what we expect. For this I'm used to using `==`, which fails as described above. [Here](https://github.com/openforcefield/openff-toolkit/blob/9d9f93334ded8ca9b2df9d0586d430b3c272c434/openff/toolkit/tests/test_topology.py#L329-L344) is one such unit test for which directly swapping in `mendeleev` will not give the expected result using `==`.

**Comment by lmmentel** [comment]
I drafted a PR #43 that should allow for using `==` and `!=` between operators. I've added simple test cases but I would be grateful if you could have a look and see it that would address you use case. Let me know if you have any comments or suggestions.
