### ISSUE TITLE
Rowland-Taylor VdW radii assigned to wrong element

### ISSUE THREAD

**Issue by SebastianWellig** [lmmentel/mendeleev#44]
## Describe the bug
Rowland-Taylor VdW radii assigned to wrong element after fluorine.

## To Reproduce
```py
from mendeleev import element

for i in range(1, 119):
    e = element(i)
    r = e.vdw_radius_rt
    if r is not None:
        print(e.symbol, int(r))
```

## Observed behavior
```
H 110
C 177
N 164
O 158
F 146
Ne 181
Na 176
Mg 187
Al 202
```

## Expected behavior
```
H 110
C 177
N 164
O 158
F 146
S 181
Cl 176
Br 187
I 202
```

## Specification

- mendleev 0.9.0
- python 3.8.12
- WSL on Windows 11

## Additional context
Original publication: _J. Phys. Chem._ **1996**, _100_, 7384.

**Comment by lmmentel** [comment]
Thanks for reporting this. I was able to reproduce and will try to fix it.
