### ISSUE TITLE
Anaconda channel lmmentel vs. condaforge 

### ISSUE THREAD

**Issue by jan-janssen** [lmmentel/mendeleev#5]
I recently integrated you mendeleev package into the conda-forge Anaconda channel: 
https://github.com/conda-forge/mendeleev-feedstock

So I was wondering if you are interested to join maintaining it.

**Comment by lmmentel** [comment]
That is great to hear! Thanks @jan-janssen! I would definitely like to help out maintaining it.  

I tried to automate the deploy to my Anaconda with travis but didn't have time to debug yet. The work I started is on the [fix-conda-deploy branch](/lmmentel/mendeleev/tree/fix-conda-deploy). 

The current setup is that tagged commits on master are build and pushed to pypi.org using travis, it would be great if at the same time a build and deploy to Anaconda could be triggered. I don't have much experience with conda-forge but that seems possible. wdyt?

**Comment by jan-janssen** [comment]
Done. You should get an email with an invitation to join the conda forge community here on GitHub. 

In terms of integration, conda-forge uses pypi as a reference - at least for python packages like yours - pulls the release from pypi and automatically creates a pull request. So all we have to do is merge the automated pull requests once the tests passed. For pure python packages this is really simple. That is why I try to get the developers of the packages involved as well.
