### ISSUE TITLE
Error in specific_heat of Argon

### ISSUE THREAD

**Issue by Eben60** [lmmentel/mendeleev#60]
## Describe the bug
The value in the database is **0.138** . The values for other noble gases are Cp and close (but not equal) to the values in https://en.wikipedia.org/wiki/Specific_heat_capacity#Monatomic_gases . For Ar that should be approx. **0.52** .

BTW the source of the `specific_heat `is not given in the Documentation: Where are the data from?

**Comment by lmmentel** [comment]
Thanks for reporting this back @Eben60 :+1: Let me look into this.

**Comment by lmmentel** [comment]
The issue is now fixed and I'll cut a fresh release based on the changes. If you spotted any other issues or have suggestions for improvements feel free to share. Thanks!
