### ISSUE TITLE
Add link to NIST Chemistry WebBook

### ISSUE THREAD

**Issue by Eben60** [lmmentel/mendeleev#67]
NIST Chemistry WebBook is a reliable source with a lot of information. 

I have collected permanent links to elements and put them into a [json file](https://github.com/Eben60/Mendeleev.jl/blob/main/data/el_chembook.json). You may want to add them to your database.

(Yes, no permanent link is defined there for carbon)

**Comment by lmmentel** [comment]
Looks good. Were you thinking about adding links to the db or parsing the data from the pages and adding those to the db?

**Comment by Eben60** [comment]
I am thinking about adding links to the db in the first line. Parsing the data could in principle come into the question, however the available data differ for different elements.

In the meanwhile I've updated my json file by adding cas-number-based links for the elements with missing official "permanent links", i.e. for carbon and some radioactive elements.

**Comment by lmmentel** [comment]
Hey @Eben60 I've realized that the links follow the same pattern of `https://webbook.nist.gov/cgi/inchi/` being concatenated with InChI of an element which is `InChi=1S/{symbol}` for I've added InChI property to `Element` in #76. Next step would be to add a property with the full url.
