### ISSUE TITLE
[BUG] Link to interactive web app is broken

### ISSUE THREAD

**Issue by chicolucio** [lmmentel/mendeleev#70]
## Describe the bug
The link https://mendeleev.herokuapp.com/ (from README) is broken. Error:

```
Application error

An error occurred in the application and your page could not be served. 
If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). 
You can do this from the Heroku CLI with the command
heroku logs --tail
```

## To Reproduce
1. Access https://mendeleev.herokuapp.com/
2. See message error

## Expected behavior
Interact with a periodic table

## Specification

- mendleev version: latest
- platform: web browser

**Comment by lmmentel** [comment]
Hey @chicolucio, thanks for reporting this. There were some updates to the heroku stack that I've missed and the app went down. I updated the the config and redeployed so it should work now. BTW the app is in open source and available in a separate repo []mendeleevapp](https://github.com/lmmentel/mendeleevapp).

If you don't mind me asking, could you share how and what for are you using mendeleev and mendeleevapp?

**Comment by chicolucio** [comment]
OK, thanks. I didn't know about the app repo.

I'm a chemist and taught chemistry until very recently. I used `mendeleev` in some scripts that I coded for teaching to get data for some elements. It's impressive the amount of data available in the package, and I like how simple it is to get data. I plan to open source the scripts soon, I'm reviewing them on my spare time since I don't work as a teacher anymore. I can list them here when I get them on GitHub. I think that this old [effective nuclear charge calculator](https://github.com/chicolucio/zeff) is the only one on GitHub right now that uses `mendeleev`.

Concerning the web app, one of my previous students sent me a message asking about some online periodic table, and I remembered that there was one based on `mendeleev`. That's how I found out about the broken link.

I have a website in Brazilian Portuguese (my mother language) where I write about science and programming. When I worked as a chemistry teacher, I had a research group and one of the students wrote a post about 3 useful Python packages for chemistry students. `mendeleev` was one of the packages. [This is the link](https://cienciaprogramada.com.br/2022/02/top-3-bibliotecas-python-quimica/), it is written in Portuguese, but I think that you would like to know that too.

**Comment by lmmentel** [comment]
Thanks for your reply @chicolucio! 

> I can list them here when I get them on GitHub. I think that this old [effective nuclear charge calculator](https://github.com/chicolucio/zeff) is the only one on GitHub right now that uses `mendeleev`.

Looking forward to that. If you would like to see any of those functionalities in `mendeleev` don't hesitate and submit and issue with the idea. Even better if you would like to contribute to the project. I'm happy to help out with getting set up and discussing he ideas.

> Concerning the web app, one of my previous students sent me a message asking about some online periodic table, and I remembered that there was one based on `mendeleev`. That's how I found out about the broken link.

Got it, thanks again for taking the time to report the app being broken,

> I have a website in Brazilian Portuguese (my mother language) where I write about science and programming. When I worked as a chemistry teacher, I had a research group and one of the students wrote a post about 3 useful Python packages for chemistry students. `mendeleev` was one of the packages. [This is the link](https://cienciaprogramada.com.br/2022/02/top-3-bibliotecas-python-quimica/), it is written in Portuguese, but I think that you would like to know that too.

That is very interesting. The intersection of chemistry/programming/data science is something that I have a very strong interest in. In case it might be useful I'm curating a list of chemistry related python repos at [awesome-python-chemistry](https://github.com/lmmentel/awesome-python-chemistry). Have a look and let me know is you find anything missing.
