### ISSUE TITLE
wrong Au boiling point

### ISSUE THREAD

**Issue by Eben60** [lmmentel/mendeleev#85]
## Describe the bug
```
>>> au.boiling_point
3080.0
```

## Expected behavior
```
3243 
```
(doing cross-check between Mendeleev.jl and PeriodicTable.jl)

**Comment by Eben60** [comment]
further errors:
Li melting temperature  553.69 (should be 453.6...)
Ne melting temperature  48.0 (should be 24.5... )

**Comment by Eben60** [comment]
more differing data:
```
julia> comp(:melt; rtol=0.01)
compare melt @ rtol=0.01
:B - 2573.0 K vs. 2349.0 K
:V - 2160.0 K vs. 2183.0 K
:Cr - 2130.0 K vs. 2180.0 K
:Ir - 2683.0 K vs. 2719.0 K
```

For Cr, Wikipedia cites 2180 K, however in  https://webbook.nist.gov/cgi/cbook.cgi?ID=C7440473&Units=SI&Mask=2#Thermo-Condensed Liquid Phase Heat Capacity data start from 2130 K, Solid Phase Heat Capacity goes up to 2130 K

For V, in https://webbook.nist.gov/cgi/cbook.cgi?ID=C7440622&Units=SI&Mask=2#Thermo-Condensed the melting point appears to be at 2190 K

For B, the same way, webbook says 2350 K

**Comment by lmmentel** [comment]
Thanks @Eben60! I noticed I don't have a source listed for that data so it's a good opportunity to revise the values and update. 

Let me know if you are interested in submitting a PR with the updates.

**Comment by Eben60** [comment]
I am not interested in submitting a PR

**Comment by lmmentel** [comment]
No worries, I appreciate you reporting the mismatches.
