### ISSUE TITLE
Document units of Electronegativities

### ISSUE THREAD

**Issue by Eben60** [lmmentel/mendeleev#86]
I'm currently in the process of taking over the electronegativities data into my `Mendeleev.jl` , thus I read your documentation. I understand that electronegativities is only a semi-quantitative concept, and probably only relative values are relevant - still most of them are not dimensionless and have actually physical units attached to them.

I've tried to get the units from the descriptions. Is that correct? Especially for Nagle, I'm not sure, as there are different ways to represent polarisability. Would be nice to have units documented (and for my project, also implemented in the software).

`e` is elementary charge
Allen : eV
Allred_Rochow : `e^2/pm^2`
Cottrell_Sutton : `(e/pm)^0.5`
Ghosh : `1/pm`
Gordy : `e/pm`
Martynov_Batsanov : `eV^0.5`
Mulliken : `eV`
Nagle : `1/Å`
Pauling : `eV^0.5`
Sanderson : dimensionless
Li_Xue : `1/pm`

**Comment by lmmentel** [comment]
Good point, I think you got the units right but I would have to double check to verify. I'll try to work it into the next release.
