### ISSUE TITLE
Isotope abundance 

### ISSUE THREAD

**Issue by Soupskill** [lmmentel/mendeleev#87]
## To Reproduce
1. Be = element('Be')
2. for iBe in Be.isotopes:
3.    print(iBe.abundance)
#Would print only 0.0
Probably there's no information in database

## Specification

- mendleev version 0.11.0
- python version 3.8.2

**Comment by Soupskill** [comment]
Thank you a lot for fast response. I would wait an update to pypi. For my project the issue is not critical. Your project is very helpful.

**Comment by lmmentel** [comment]
Thanks fro the positive feedback :slightly_smiling_face: Let me close this since v0.12.0 was just released and has a fix.
