### ISSUE TITLE
Oxygen has no atomic radius

### ISSUE THREAD

**Issue by DavidChipman** [lmmentel/mendeleev#9]
I just noticed that the value for Oxygen's atomic radius comes back as "None". This can't be true. It should be about 66 pm, shouldn't it? Got that number from Wikipedia, but "None" makes no sense.

**Comment by lmmentel** [comment]
Hi @DavidChipman,

Thanks for reporting this! I checked this and indeed the `atomic_radius` for oxygen returns `None` which means that the corresponding value is missing from the `mendeleev`'s database. I'll try to fix that.

I would recommend you to try `atomic_radius_rahm` instead if that fits your application or try one of the covalent or van der Waals radii described in the [docs](https://mendeleev.readthedocs.io/en/stable/data.html).
