### ISSUE TITLE
Valance electron of Pd

### ISSUE THREAD

**Issue by anhhaokudo** [lmmentel/mendeleev#91]
## Describe the bug
.nvalence gives 12 as the number of valence electrons of Pd 

## To Reproduce
1. from mendeleev import element
2. element('Pd').nvalence()

## Expected behavior
The number of valence electron of Pd should be 10
## Specification

- mendleev version 0.12.0
- python version
- platform

**Comment by lmmentel** [comment]
Thanks a lot for reporting this @anhhaokudo :raised_hands: 

I was able to reproduce this behavior and is seems I'll need to adjust how the number of valence _e_ is fetched. Let me try to fix it.

**Comment by lmmentel** [comment]
Hey I just published [v0.12.1](https://pypi.org/project/mendeleev/) of mendeleev which has a fix for :point_up:
