### ISSUE TITLE
Quadrupole moment for 19F

### ISSUE THREAD

**Issue by jkshenton** [lmmentel/mendeleev#96]
## Describe the bug
Hi! Thanks for making this very useful library! 

I would like to use it in some of our tools, but noticed that at least for F, the quadrupole moment seems incorrect (not the same as the cited data source).

Could you double-check this for F and for other species? 

Many thanks! 

## To Reproduce
``` python
from mendeleev import isotope
F19 = isotope("F", 19)
print(F19.quadrupole_moment)
```
This comes out as zero. 

## Expected behavior
According to:
https://www-nds.iaea.org/nuclearmoments/
and 
https://www-nds.iaea.org/publications/indc/indc-nds-0650.pdf

the correct value should be:
-0.0942 b 

## Specification

- mendleev version: 0.12.1
- python version: 3.10.8
- platform: linux

**Comment by lmmentel** [comment]
Hi @jkshenton, thanks a lot for taking the time to report back on this. 

I had a look into it and it seems that the the value you are referring to corresponds to an excited state of 19F with spin 5/2+ which is 197 keV above the ground state. I probably should have made that explicit somewhere in the docs that all the isotope data corresponds to ground states.

If you feel like the there is a use case for including excited states as well, feel free to submit an issue and we can discuss further.

**Comment by jkshenton** [comment]
Argh! You're right, of course -- thanks for checking anyway! I'll think about whether we would need excited states and open a separate issue if that would be the case. 

Thanks!
